### ISSUE TITLE
How can I compile this

### ISSUE THREAD

**Issue by Cobalixe** [jpmac26/gba-mus-ripper#1]
seriously I tried evereything, can you upload the exe files or put in more detail the compilation?

**Comment by CaptainSwag101** [comment]
What methods did you try? It should only require a basic C++ compiler environment (probably MinGW on Windows), and then you just need to run the "make" command in the project directory.

**Comment by Cobalixe** [comment]
How do I run the make command

**Comment by CaptainSwag101** [comment]
It sounds like you're unfamiliar with compiling from the command line, I so I'll try and get you some .exe files to save you some time.

**Comment by CaptainSwag101** [comment]
Here, these should work: [https://mega.nz/#!YtBnFZoC!A8jPTVeG8HtBTfGIF58TRYmBP-BK34EgUwVl0ExNqbI](https://mega.nz/#!YtBnFZoC!A8jPTVeG8HtBTfGIF58TRYmBP-BK34EgUwVl0ExNqbI)

**Comment by Cobalixe** [comment]
With the sound font ripper, I don't understand what adress mean, I don't
know what to put in there for extract the sound font of my gba file. If I
can with all the instruments

**Comment by Cobalixe** [comment]
Also I have a problem: in Pokémon leaf green, the song that plays when a
Pokémon is healed doesn't sound like in the original and I don't know why.
I can send you the song if you can figure it out

**Comment by CaptainSwag101** [comment]
To use the program, you probably don't need to manually input an address. Just use "gba_mus_ripper.exe" with the ROM you want to extract, and it will either work, or it won't. I didn't initially create this program, I've only made slight tweaks to the code. I am also working on a graphical version of this program, which will make it easier to dump the music without having to worry about all the confusing settings.

Also, the problem with Pokemon Leafgreen is a problem which affects all the Pokemon GBA games, and unfortunately I don't know how to fix it, sorry. If I can eventually figure out how to extract that pitch-shift effect, I'll definitely add that feature, but right now I'm fairly inexperienced with reverse-engineering.
